apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          # hack to pull local images in k8s of docker-desktop.
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 1
            httpGet:
              port: 8081
              path: /liveness
          readinessProbe:
            initialDelaySeconds: 1
            httpGet:
              port: 8081
              path: /readiness

